#!/bin/sh
set -eu

USAGE="Usage: s3mount BUCKET MOUNTPOINT ROLE [REGION]"

if [ $# -lt 1 ] ; then
  echo missing BUCKET argument.
  echo ${USAGE}
  exit 1
fi

if [ $# -lt 2 ] ; then
  echo missing MOUNTPOINT argument.
  echo ${USAGE}
  exit 1
fi

if [ $# -lt 3 ] ; then
  echo missing ROLE argument.
  echo ${USAGE}
  exit 1
fi

BUCKET=$1
MOUNTPOINT=$2
ROLE=$3
REGION=${4:-ap-northeast-1}
##UID=`id -u`
GID=`id -g`
S3URL="https://s3.${REGION}.amazonaws.com"

s3fs ${BUCKET} ${MOUNTPOINT} -o allow_other,uid=${UID},gid=${GID},url="${S3URL}",iam_role="${ROLE}"
